// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5wXQsQawZOr44ZGI6AhhaeFZYwXi9WUE',
    appId: '1:625329456257:web:c97c8f909bac57d9c4b980',
    messagingSenderId: '625329456257',
    projectId: 'auth-flutter-3c378',
    authDomain: 'auth-flutter-3c378.firebaseapp.com',
    storageBucket: 'auth-flutter-3c378.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkFahzT5FELEDk2-l76qxmRFw8c2UTLjE',
    appId: '1:625329456257:android:bc4350dfebe0767dc4b980',
    messagingSenderId: '625329456257',
    projectId: 'auth-flutter-3c378',
    storageBucket: 'auth-flutter-3c378.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzonCftgQbbi0CfCD7W4dq5ASp_j1PA8k',
    appId: '1:625329456257:ios:82fffd0d63d0dd38c4b980',
    messagingSenderId: '625329456257',
    projectId: 'auth-flutter-3c378',
    storageBucket: 'auth-flutter-3c378.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzonCftgQbbi0CfCD7W4dq5ASp_j1PA8k',
    appId: '1:625329456257:ios:82fffd0d63d0dd38c4b980',
    messagingSenderId: '625329456257',
    projectId: 'auth-flutter-3c378',
    storageBucket: 'auth-flutter-3c378.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5wXQsQawZOr44ZGI6AhhaeFZYwXi9WUE',
    appId: '1:625329456257:web:99465726112b31a1c4b980',
    messagingSenderId: '625329456257',
    projectId: 'auth-flutter-3c378',
    authDomain: 'auth-flutter-3c378.firebaseapp.com',
    storageBucket: 'auth-flutter-3c378.firebasestorage.app',
  );
}
